//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewAssessment.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity
    {
        public long id { get; set; }
        public string name { get; set; }
        public long coordsId { get; set; }
    
        public virtual coord coord { get; set; }
    }
}
